"""update AFT test schema

Revision ID: 3b5d8536f9a3
Revises: 
Create Date: 2026-08-20 07:03:38.458301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5d8536f9a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aft_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadlift_performance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hrp_performance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sdc_performance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('plank_performance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('two_mile_run_performance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deadlift_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hrp_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sdc_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plank_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('two_mile_run_score', sa.Integer(), nullable=True))
        batch_op.drop_column('hrp')
        batch_op.drop_column('sprint_drag_carry')
        batch_op.drop_column('two_mile_run')
        batch_op.drop_column('deadlift')
        batch_op.drop_column('plank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aft_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plank', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deadlift', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('two_mile_run', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sprint_drag_carry', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hrp', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('two_mile_run_score')
        batch_op.drop_column('plank_score')
        batch_op.drop_column('sdc_score')
        batch_op.drop_column('hrp_score')
        batch_op.drop_column('deadlift_score')
        batch_op.drop_column('two_mile_run_performance')
        batch_op.drop_column('plank_performance')
        batch_op.drop_column('sdc_performance')
        batch_op.drop_column('hrp_performance')
        batch_op.drop_column('deadlift_performance')

    # ### end Alembic commands ###
